### ISSUE TITLE
Show exit transactions for UTXOs

### ISSUE THREAD

**Issue by kasima** [omisego/omg-block-explorer#14]
*As a* user,
*I can* click a link showing a root chain exit attempt transaction on etherscan,
*So that* it's easy for me to see that status of UTXOs

For example, the outputs for [this transaction](http://quest.samrong.omg.network/transaction/0x25849f242df3dfeca47da34db87f2e19d3c8cf7e36e18af84a6623cd145f938d) on the block explorer could link to these two exit attempts:

- [Exit for 5 tokens](https://rinkeby.etherscan.io/tx/0xb44bfbb1e3c1c9c492fc12518e85dd4ade834283205971f696c610d40e60e905)
- [Exit for 95 tokens](https://rinkeby.etherscan.io/tx/0xa5d25b77bd9c5ddbc531af997ba5d1a90188f1a00a5a53c6326499e4cd9c5a97)

For valid exits, we could expose this in a new watcher endpoint to show exits in flight with the ethereum tx hashes. 

For invalid exits, we could show additional information (ethereum tx hash?) added to the `byzantine_events` field of the watcher.

Or, we could show all the exits (valid and invalid) with their statuses in the new watcher endpoint.

At minimum, we can add an `exits` array as part of the `transaction.get` payload.

**Comment by jrhite** [comment]
dependent on omisego/elixir-omg#801

**Comment by pdobacz** [comment]
Hey, I've seen this issue before, but now one detail caught my eye:

> This would require some additional information added to the byzantine_events field of the watcher.

valid exits don't show up in `byzantine_events`, so I this isn't the proper place.

**Comment by kasima** [comment]
> valid exits don't show up in `byzantine_events`, so I this isn't the proper place.

Good call. Not quite sure what I meant with that line. Clarified in the description.

**Comment by jrhite** [comment]
@kasima I don't want to broaden the scope of this issue, but the code is all very similar. Indeed, I have a proof of concept I'm having reviewed which would allow us to store the eth txn hash for any plasma event that also creates a txn on the rootchain.

Wouldn't it be reasonable to want to see the eth txn hash for a deposit into plasma (or challenge, or...etc)?

Regarding exits, we have a `start exit` eth txn. And later, when the funds are actually transferred, we have a `process exit` eth txn. Specific to this issue, I'm assuming it's the `process exit` eth txn hash we want to display since that's when money moves from the contract to the user's account. However, it may also make sense to display both the start and process txn hashes.

**Comment by boolafish** [comment]
Just a head up, in new abstract layer design, we might have different way to provide the required info to trace the exit in priority queue. see detail in https://github.com/omisego/plasma-contracts/issues/198
